---
services:
  mongoDB:
    image: mongo:latest
    container_name: database
    restart: always
    volumes: [./datadir:/data/db]
  covid-bot:
    build:
      context: ./src/
    image: covid-bot
    container_name: bot
    restart: always
    depends_on: [mongoDB]
    env_file: [.env]
