---
name: Deploy on production server
on:
  push:
    branches: [main]
jobs:
  test:
    name: Test Stage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.13"
      - name: Install dependencies
        run: |
          pip install flake8
      - name: Run flake8
        run: flake8 .
  build:
    name: Build Stage
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose
          if ! docker compose version; then
            echo "❌ Docker Compose не установлен!" >&2
            exit 1
          fi
      - name: Build Docker images
        run: |
          docker compose build
  deploy:
    name: Deploy Stage
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Generate .env file
        run: |
          echo "Generating .env from .env.example"
          cp .env.example .env
          sed -i "s|^TOKEN=.*|TOKEN=${{ secrets.BOT_TELEGRAM_TOKEN }}|" .env
          sed -i "s|^OWNER_ID=.*|OWNER_ID=${{ secrets.BOT_OWNER_ID }}|" .env
          cat .env  # Логирование для отладки
      - name: List files to be transferred
        run: |
          echo "Files in workspace:"
          ls -la .
      - name: Copy project to remote server
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.REMOTE_KEY }}
          source: "./*,!.git/,!datadir/" # Явно указываем все файлы в корне, исключаем .git и datadir
          target: /home/admin/covid-bot
          strip_components: 1
          rm: false # Отключаем удаление, чтобы избежать ошибок с правами
          debug: true # Включаем отладку для подробных логов
      - name: Deploy on remote server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.REMOTE_KEY }}
          script: |
            echo "Deploying to /home/admin/covid-bot"
            cd /home/admin/covid-bot || { echo "❌ Directory not found"; exit 1; }
            docker compose pull || { echo "❌ Failed to pull images"; exit 1; }
            docker compose up -d --build || { echo "❌ Failed to start services"; exit 1; }
            docker compose ps
