---
name: Deploy on production server
on:
  push:
    branches: [main]
jobs:
  test:
    name: Test Stage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.13"
      - name: Install dependencies
        run: |
          pip install flake8
      - name: Run flake8
        run: flake8 .
  build:
    name: Build Stage
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose
          if ! docker compose version; then
            echo "❌ Docker Compose не установлен!" >&2
            exit 1
          fi
      - name: Build Docker images
        run: |
          docker compose build
  deploy:
    name: Deploy Stage
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Generate .env file
        run: |
          cp .env.example .env
          echo "TOKEN=${{ secrets.BOT_TELEGRAM_TOKEN }}" >> .env
          echo "OWNER_ID=${{ secrets.BOT_OWNER_ID }}" >> .env
      - name: Build docker image > tar
        run: |
          docker compose build
          docker save -o covid-bot.tar covid-bot
          if [ ! -s covid-bot.tar ]; then
            echo "❌ Файл covid-bot.tar пустой или не создан!" >&2
            exit 1
          fi
          chmod 644 covid-bot.tar docker-compose.yml .env
      - name: Remove existing directory on server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.REMOTE_KEY }}
          script: |
            rm -rf /home/admin/covid-bot
      - name: Copy project to remote server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.REMOTE_KEY }}
          source: covid-bot.tar,docker-compose.yml,.env
          target: /home/admin/covid-bot
      - name: Run on remote server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.REMOTE_KEY }}
          script: |-
            cd /home/admin/covid-bot
            docker load -i covid-bot.tar || { echo "❌ Ошибка загрузки образа"; exit 1; }
            docker compose up -d || { echo "❌ Ошибка запуска docker-compose"; exit 1; }
            docker compose logs
