---
name: Deploy on production server
on:
  push:
    branches: [main]
jobs:
  test:
    name: Test Stage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.13"
      - name: Install dependencies
        run: |
          pip install flake8
      - name: Run flake8
        run: flake8 .
  build:
    name: Build Stage
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose
          if ! docker compose version; then
            echo "❌ Docker Compose не установлен!" >&2
            exit 1
          fi
      - name: Build Docker images
        run: |
          docker compose build
  deploy:
    name: Deploy Stage
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Generate .env file
        run: |
          echo "Generating .env from .env.example"
          cp .env.example .env
          sed -i "s|^TOKEN=.*|TOKEN=${{ secrets.BOT_TELEGRAM_TOKEN }}|" .env
          sed -i "s|^OWNER_ID=.*|OWNER_ID=${{ secrets.BOT_OWNER_ID }}|" .env
          echo "✅ .env generated:"
          cat .env
      - name: Prepare files and create archive
        run: |
          mkdir -p temp_deploy
          cp -r src temp_deploy/
          cp docker-compose.yml temp_deploy/
          cp .env temp_deploy/
          tar -zcf /tmp/deploy.tar.gz --exclude='__pycache__' --exclude='.DS_Store' temp_deploy/*
      - name: Copy archive to remote server
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.REMOTE_KEY }}
          source: "/tmp/deploy.tar.gz"
          target: "/tmp/"
      - name: Prepare directory and deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.REMOTE_KEY }}
          script: |
            echo "Preparing remote directory"
            sudo mkdir -p /home/***/covid-bot
            sudo chown ${{ secrets.REMOTE_USER }}:${{ secrets.REMOTE_USER }} /home/***/covid-bot
            sudo chmod 755 /home/***/covid-bot
            echo "Unpacking archive"
            tar -zxf /tmp/deploy.tar.gz -C /home/***/covid-bot
            ls -la /home/***/covid-bot
            echo "Deploying with Docker Compose"
            cd /home/***/covid-bot
            docker compose pull || { echo "❌ Failed to pull images"; exit 1; }
            docker compose up -d --build || { echo "❌ Failed to start services"; exit 1; }
            docker compose ps
